{{- if .Values.cluster_analysis_template -}}
apiVersion: argoproj.io/v1alpha1
kind: ClusterAnalysisTemplate
metadata:
  name: 500-errors
spec:
  args:
  - name: metrics-interval
  - name: success-condition
  - name: failure-limit
  - name: service-name
  - name: query-interval
  metrics:
  - name: 500-errors
    interval: "{{`{{`}}args.metrics-interval{{`}}`}}"
    successCondition: "{{`{{`}}args.success-condition{{`}}`}}"
    failureLimit: "{{`{{`}}args.failure-limit{{`}}`}}"
    provider:
      prometheus:
        address: http://thanos-query-http.monitoring:10902
        query: |
          (sum(rate(istio_requests_total{reporter="destination", destination_service_name=~"{{`{{`}}args.service-name{{`}}`}}", response_code=~"5.."}[{{`{{`}}args.query-interval{{`}}`}}]) > 0)
          / sum(rate(istio_requests_total{reporter="destination", destination_service_name=~"{{`{{`}}args.service-name{{`}}`}}"}[{{`{{`}}args.query-interval{{`}}`}}])) > 0)*100 OR on() vector(0)
  {{- end }}



