{{- if .Values.cluster_analysis_template -}}
apiVersion: argoproj.io/v1alpha1
kind: ClusterAnalysisTemplate
metadata:
  name: 500-errors-istio
spec:
  args:
  - name: metrics-interval
  - name: success-condition
  - name: failure-limit
  - name: service-name
  - name: query-interval
  metrics:
  - name: 500-errors-istio
    interval: "{{`{{`}}args.metrics-interval{{`}}`}}"
    successCondition: "{{`{{`}}args.success-condition{{`}}`}}"
    failureLimit: "{{`{{`}}args.failure-limit{{`}}`}}"
    provider:
      prometheus:
        address: http://thanos-query.monitoring:9090
        query: |
          (sum(rate(istio_requests_total{reporter="destination", role="canary", destination_service_name=~"{{`{{`}}args.service-name{{`}}`}}", response_code=~"5.."}[{{`{{`}}args.query-interval{{`}}`}}]) > 0)
          / sum(rate(istio_requests_total{reporter="destination", role="canary", destination_service_name=~"{{`{{`}}args.service-name{{`}}`}}"}[{{`{{`}}args.query-interval{{`}}`}}])) > 0)*100 OR on() vector(0)
---
apiVersion: argoproj.io/v1alpha1
kind: ClusterAnalysisTemplate
metadata:
  name: 500-errors-java
spec:
  args:
    - name: metrics-interval
    - name: success-condition
    - name: failure-limit
    - name: service-name
    - name: query-interval
  metrics:
    - name: 500-errors-java
      interval: "{{`{{`}}args.metrics-interval{{`}}`}}"
      successCondition: "{{`{{`}}args.success-condition{{`}}`}}"
      failureLimit: "{{`{{`}}args.failure-limit{{`}}`}}"
      provider:
        prometheus:
          address: http://thanos-query.monitoring:9090
          query: |
            (sum(rate(http_server_requests_seconds_count{app=~"{{`{{`}}args.service-name{{`}}`}}", status=~"5..",uri!~"(/manage/prometheus)", role="canary"}[{{`{{`}}args.query-interval{{`}}`}}])> 0) /
            sum(rate(http_server_requests_seconds_count{app=~"{{`{{`}}args.service-name{{`}}`}}",uri!~"(/manage/prometheus)",role="canary"}[{{`{{`}}args.query-interval{{`}}`}}])) >0)*100 OR on() vector(0)
  {{- end }}



