version: 2
updates:
  - package-ecosystem: pip
    directory: /
    schedule:
      interval: monthly
    reviewers:
      - willkg
  - package-ecosystem: docker
    directory: /docker
    schedule:
      interval: monthly
    reviewers:
      - willkg
