# GoReleaser configuration file for building macOS binaries.
#
# NOTE: Currently, GoReleaser doesn't support only building a subset of defined
# operating systems and architectures.
# For more details, see: https://github.com/goreleaser/goreleaser/issues/1852.
#
# Hence, we use this workaround of having a copy of GoReleaser's main
# configuration file (.goreleaser.yml) and changing the 'goos' keys to only
# contain 'darwin'.
#
# NOTE: This GoReleaser configuration is not meant to be run directly, but
# rather through Make's release-build-darwin target.

project_name: Oasis Core Ledger

env:
  # Require use of Go modules.
  - GO111MODULE=on

builds:
  - id: oasis-core-ledger
    binary: oasis-core-ledger
    flags:
      - -trimpath
    ldflags:
      # NOTE: At the moment, GoReleaser produces different binaries when
      # releases are built from different git paths, unless -buildid= is added
      # to ldflags.
      # For more details, see: https://github.com/oasislabs/goreleaser/issues/1.
      - -buildid=
      - "{{.Env.GOLDFLAGS_VERSION}}"
    goos:
      - darwin
    goarch:
      - amd64

  - id: ledger-signer
    main: ./ledger-signer/ledger_signer.go
    binary: ledger-signer
    flags:
      - -trimpath
    ldflags:
      # NOTE: At the moment, GoReleaser produces different binaries when
      # releases are built from different git paths, unless -buildid= is added
      # to ldflags.
      # For more details, see: https://github.com/oasislabs/goreleaser/issues/1.
      - -buildid=
      - "{{.Env.GOLDFLAGS_VERSION}}"
    goos:
      - darwin
    goarch:
      - amd64

archives:
  - name_template: "{{replace .ProjectName \" \" \"_\" | tolower}}_{{.Version}}_{{.Os}}_{{.Arch}}"
    wrap_in_directory: true
    files:
      - CHANGELOG.md
      - README.md
      - LICENSE

checksum:
  name_template: SHA256SUMS-{{.Version}}.txt
  algorithm: sha256

snapshot:
  name_template: "{{.Version}}-dev"

release:
  name_template: "{{.ProjectName}} {{.Version}}"
