builds:
- env:
  - CGO_ENABLED=0

dockers:
- dockerfile: Dockerfile-goreleaser
  image_templates:
  - "quay.io/lunarway/snyk_exporter:latest"
  - "quay.io/lunarway/snyk_exporter:v{{ .Major }}"
  - "quay.io/lunarway/snyk_exporter:v{{ .Major }}.{{ .Minor }}"
  - "quay.io/lunarway/snyk_exporter:v{{ .Major }}.{{ .Minor }}.{{ .Patch }}"

archive:
  format: binary
  name_template: "{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}"
  replacements:
    darwin: darwin
    linux: linux
    windows: windows
    386: i386

checksum:
  name_template: '{{ .ProjectName }}-checksums.txt'

snapshot:
  name_template: "git-{{.Commit}}"

release:
  name_template: "v{{.Version}}"
  prerelease: auto

changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
