---
version: '2.4'
services:
  # Base container is used for development tasks like tests, linting,
  # and building docs.
  base:
    build:
      context: .
      dockerfile: docker/Dockerfile
    image: eliot:build
    env_file:
      - docker/config/local_dev.env
      - .env

  # Symbolicator service
  eliot:
    extends:
      service: base
    ports:
      - "8000:8000"
    depends_on:
      - fakesentry
      - statsd
    links:
      - fakesentry
      - statsd
    volumes:
      - $PWD:/app
    command: ["eliot"]

  # Container specifically for running tests.
  test:
    extends:
      service: base
    env_file:
      - docker/config/local_dev.env
      - docker/config/test.env
    links:
      - db
      - fakesentry
      - redis-cache
    volumes:
      - $PWD:/app

  test-ci:
    extends:
      service: base
    env_file:
      - docker/config/local_dev.env
      - docker/config/test.env
    links:
      - db
      - fakesentry
      - redis-cache

  # https://github.com/willkg/kent
  fakesentry:
    build:
      context: docker/images/fakesentry
    image: local/tecken_fakesentry
    ports:
      - "8090:8090"
    command: run --host 0.0.0.0 --port 8090

  # https://hub.docker.com/r/hopsoft/graphite-statsd/
  statsd:
    image: hopsoft/graphite-statsd:latest
    ports:
      - "8081:80"
      - "2003-2004:2003-2004"
      - "2023-2024:2023-2024"
      - "8125:8125/udp"
      - "8126:8126"
