services:
  squid-check:
    build:
      context: .
      dockerfile: dev.dockerfile
    ports:
      - "8080:8080"
    command:
      - --proxy-address=squid:3128
      - --target-address=squid-check:8080
      - --log-level=debug

  squid:
    image: "ubuntu/squid:latest"
