{{- if and .Values.authorizationpolicy.enabled .Values.virtualservice.enabled  -}}
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: {{ include "argo-workflows.server.fullname" . }}
  namespace: istio-system
spec:
  action: ALLOW
  rules:
  - from:
    - source:
        remoteIpBlocks:
        - 167.98.102.254
        - 79.125.73.252
        {{- range $IPs := .Values.authorizationpolicy.whitelistIPs }}
        - {{ $IPs}}
        {{- end }}
    to:
    - operation:
        hosts:
        - {{ .Values.virtualservice.hostname | quote }}
  selector:
    matchLabels:
       app: istio-ingressgateway
  {{- end }}

