{{- if and .Values.virtualservice.enabled .Values.server.enabled -}}
{{- $serviceName := include "argo-workflows.server.fullname" . -}}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ template "argo-workflows.server.fullname" . }}
  labels:
    {{- include "argo-workflows.labels" (dict "context" . "component" .Values.server.name "name" .Values.server.name) | nindent 4 }}
spec:
  gateways:
  {{- range $hosts := .Values.virtualservice.gateways }}
  - {{ $hosts }}
  {{- end }}
  hosts:
    - {{ .Values.virtualservice.hostname }}
  http:
    - route:
        - destination:
            host: {{ $serviceName }}
  {{- end }}
