{{- if .Values.cluster_analysis_template.enabled -}}
apiVersion: argoproj.io/v1alpha1
kind: ClusterAnalysisTemplate
metadata:
  name: 500-errors
spec:
  metrics:
  - name: 500-errors
    interval: "{{args.metrics-interval}}"
    successCondition: "{{args.success-condition}}"
    failureLimit: "{{args.failure-limit}}"
    provider:
      prometheus:
        address: http://thanos-query-http.monitoring:10902
        query: |
          (sum(rate(istio_requests_total{reporter="source", destination_service=~"{{args.service-name}}", response_code=~"5.."}["{{args.query-interval}}"]))
          / sum(rate(istio_requests_total{reporter="source", destination_service=~"{{args.service-name}}"}["{{args.query-interval}}"])))*100 OR on() vector(0)
  {{- end }}



