{{- if or .Values.controller.persistence.nodeStatusOffLoad .Values.controller.persistence.archive }}
apiVersion: v1
kind: Secret
metadata:
  name: argo-postgres-config
data:
  username: {{ .Values.secrets_db_username }}
  password: {{ .Values.secrets_db_password }}                                                                                                                                                                             │
{{- end }}
