name: Specs
on:
  workflow_call:
    secrets:
      SAUCE_USERNAME:
        required: true
      SAUCE_ACCESS_KEY:
        required: true
jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest
    env:
      SAUCE_USERNAME: ${{ secrets.SAUCE_USERNAME }}
      SAUCE_ACCESS_KEY: ${{ secrets.SAUCE_ACCESS_KEY }}
    steps:
    - uses: actions/checkout@v3
    - uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true
    - uses: actions/setup-node@v3
      with:
        node-version: '14'
        cache: npm
    - uses: browser-actions/setup-chrome@v1
    - run: |
        bundle install
        npm install
        bundle exec thin -d -p 9080 -R config.ru start
        bin/start_sc.sh
        npm test
        npm run build
        bundle exec rake
        bundle exec thin -d -p 9080 -R config.ru stop
        bin/stop_sc.sh