name: Static Analysis
on: [ workflow_call ]
jobs:
  static:
    name: Static Analysis
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Setup Ruby and install gems
      uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true
    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: '14'
        cache: yarn
    - name: Rubocop
      run: bundle exec rubocop
    - name: Brakeman
      run: bundle exec brakeman -6 -A --no-color -z -q
    - name: Bundle Audit Update
      run: bundle exec bundle-audit update
    - name: Dependency Check
      uses: dependency-check/Dependency-Check_Action@main
      with:
        project: ${{ github.repository }}
        path: Gemfile.lock
        format: 'HTML'
        args: >
          --scan package-lock.json
          --failOnCVSS 0
          --suppression suppression.xml
    - name: Upload Dependency Check Report
      if: ${{ success() || failure() }}
      uses: actions/upload-artifact@v3
      with:
          name: Dependency Check Report
          path: ${{github.workspace}}/reports
